/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 * For more information about which c-functions
 * need which of these lowlevel functions
 * please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes - Dołączenie bibliotek standardowych i systemowych */
#include <sys/stat.h>  // Definicje struktur statusu plików (np. struct stat).
#include <stdlib.h>    // Standardowe funkcje ogólne (np. malloc, exit).
#include <errno.h>     // Definicje kodów błędów (np. EINVAL, ENOMEM).
#include <stdio.h>     // Standardowe operacje wejścia/wyjścia (np. printf).
#include <signal.h>    // Obsługa sygnałów systemowych.
#include <time.h>      // Funkcje związane z czasem.
#include <sys/time.h>  // Dodatkowe struktury czasu systemowego.
#include <sys/times.h> // Definicje struktur do pomiaru czasu procesora.


/* Variables - Zmienne i deklaracje zewnętrzne */
// Deklaracja zewnętrznej funkcji do wysyłania znaku (słaba relacja __attribute__((weak)) - można ją nadpisać).
extern int __io_putchar(int ch) __attribute__((weak));
// Deklaracja zewnętrznej funkcji do odbierania znaku (również z atrybutem weak).
extern int __io_getchar(void) __attribute__((weak));






/*
 * To, co widzisz, to absolutne minimum socjalne dla biblioteki standardowej C (Newlib), aby w ogóle chciała
 * współpracować z mikrokontrolerem. Te dwie linijki służą do udawania, że mikrokontroler posiada zmienne
 * środowiskowe.W zwykłych komputerach (Windows, Linux, macOS) system operacyjny przechowuje tzw. zmienne
 * środowiskowe (ang. environment variables). Są to globalne ustawienia systemu, takie jak ścieżka do programów
 * (słynne PATH), nazwa użytkownika czy konfiguracja języka. Programy w C mogą odpytywać system o te zmienne.
 * Mikrokontroler (np. Twój STM32) nie ma systemu operacyjnego, nie ma użytkowników ani zmiennych środowiskowych. Jednak biblioteka standardowa C została napisana tak, że zawsze oczekuje obecności zmiennej o nazwie environ. Jeśli jej nie dostanie, kompilator zgłosi błąd i nie pozwoli zbudować programu.
 *
 * Wyobraź sobie to jako pustą teczkę z napisem "Zmienne Środowiskowe":
 * Tworzysz pustą teczkę (__env).
 * Kładziesz na biurku kartkę z napisem environ, która palcem wskazuje na tę pustą teczkę.
 * Gdy biblioteka C przychodzi i pyta: "Gdzie są zmienne środowiskowe?", widzi kartkę environ, idzie
 * za jej wskazaniem, zagląda do teczki, widzi tam 0 (pusto) i mówi: "Ok, rozumiem, nie ma żadnych zmiennych,
 * działam dalej".
 *
 *
 *
 *
 *
 * char *__env[1] – Tworzy jednoelementową tablicę, która przechowuje wskaźniki na tekst (łańcuchy znaków).
 * = { 0 }; – Wpisuje do tej tablicy zero (NULL). W świecie systemów operacyjnych oznacza to:
 *  "To jest koniec listy zmiennych środowiskowych". Ponieważ zero jest na pierwszym miejscu, tablica mówi:
 *   "Ta lista jest pusta, nie ma tu żadnych zmiennych".
 */

char *__env[1] = { 0 };       // Pusta tablica reprezentująca środowisko systemowe.
char **environ = __env;       // Wskaźnik na tablicę środowiska, wymagany przez bibliotekę C.








/* Functions - Implementacje wywołań systemowych */

// Inicjalizacja uchwytów monitora (używane przy debugowaniu przez semihosting, tu puste).
/*
 * Po co to tu jest: W niektórych środowiskach programistycznych ta funkcja służy do uruchomienia
 * tzw. semihostingu (technologii, która pozwala mikrokontrolerowi wysyłać komunikaty bezpośrednio
 * do debuggera w komputerze, korzystając z kabla programatora ST-Link). Ponieważ STM32CubeIDE
 * domyślnie używa do tego celu portu UART (poprzez opisywaną wcześniej funkcję _write), ta funkcja
 * została zostawiona jako pusta. Jest tu tylko dlatego, że biblioteka standardowa C może próbować
 * ją wywołać na samym starcie programu.
 */
void initialise_monitor_handles()
{
}








/*
 * Po co to tu jest: W systemach operacyjnych (jak Linux) skrót PID oznacza Process Identifier
 * (Identyfikator Procesu). Każdy uruchomiony program (np. przeglądarka, odtwarzacz muzyki) ma swój
 * unikalny numer PID. Kiedy biblioteka standardowa C (np. funkcje generujące liczby losowe lub
 *  zarządzające pamięcią) pyta: "W jakim procesie aktualnie się znajduję?", ta funkcja odpowiada: 1.
 *   Na mikrokontrolerze bez systemu operacyjnego działa tylko jeden, główny program (pętla while(1) w main.c),
 *    dlatego na sztywno wpisano tu jedynkę – udajemy, że nasz program to ten pierwszy, główny proces systemowy.
 */
// Pobranie ID procesu. W mikrokontrolerze bez OS zawsze zwraca 1 (jeden główny proces).
int _getpid(void)
{
  return 1;
}








/*
 * Co to robi: Zwraca błąd -1 i ustawia kod błędu na "Nieprawidłowy argument".Po co to tu jest:
 *  W prawdziwych systemach funkcja kill służy do wysyłania sygnałów do procesów – najczęściej
 *  po to, aby je zamknąć lub ubić (stąd nazwa kill). Przyjmuje dwa argumenty: pid (który proces ubić)
 *   oraz sig (jaki sygnał wysłać).
 *   Analiza wnętrza:
 *   (void)pid; oraz (void)sig; – Ponieważ mikrokontroler nie potrafi zabijać procesów, te zmienne nie będą do
 *   niczego użyte. Te dwie linijki "oszukują" kompilator, żeby nie zgłaszał ostrzeżeń o nieużywanych
 *   argumentach.
 *   errno = EINVAL; – Słowo errno to globalna zmienna systemowa przechowująca kod ostatniego błędu.
 *   EINVAL oznacza Error: Invalid Argument (Błąd: Nieprawidłowy argument). Mówimy bibliotece C:
 *   "Próba wysłania sygnału była niepoprawna".
 *   return -1; – W standardzie POSIX zwrócenie -1 oznacza, że operacja się nie powiodła.
 */

// Wysyłanie sygnału do procesu. Mikrokontroler nie obsługuje sygnałów.
int _kill(int pid, int sig)
{
  (void)pid;    // Wyciszenie ostrzeżenia kompilatora o nieużywanej zmiennej pid.
  (void)sig;    // Wyciszenie ostrzeżenia kompilatora o nieużywanej zmiennej sig.
  errno = EINVAL; // Ustawienie błędu: Nieprawidłowy argument.
  return -1;    // Zwrócenie kodu błędu.
}














/*
 * W normalnym komputerze, gdy program kończy działanie (np. dojdzie do końca funkcji main lub
 * napotka błąd krytyczny), funkcja _exit zamyka okno programu i oddaje kontrolę do systemu operacyjnego
 *  (np. Windowsa).Na mikrokontrolerze nie ma systemu, do którego można wrócić. Program na STM32 musi
 *  działać bez przerwy od momentu włączenia zasilania aż do jego odcięcia. Dlatego ta funkcja radzi
 *  sobie w następujący sposób:
 *  _kill(status, -1); – Wywołuje opisywaną przed chwilą funkcję _kill. Przekazuje jej status zakończenia
 *  (np. 0 jako sukces lub kod błędu). Ponieważ nasz _kill i tak nic nie robi (zwraca tylko -1), ta linijka
 *  ma charakter czysto formalny, wymagany przez standard języka C.
 *  while (1) {} – To jest kluczowy moment. Jest to pętla nieskończona, która celowo "zawiesza" mikrokontroler.
 *   Procesor wpada w tę pętlę i kręci się w niej w kółko, robiąc absolutnie nic. To bezpieczne zachowanie –
 *   jeśli program z jakiegoś powodu musiał się zakończyć, najlepsze co może zrobić mikrokontroler, to zatrzymać się i czekać na fizyczny reset (np. kliknięcie przycisku RESET na płytce).
 */


// Wyjście z programu (np. po powrocie z funkcji main).
void _exit (int status)
{
  _kill(status, -1); // Próba zabicia procesu (zasymulowanie końca).
  while (1) {}       // Pętla nieskończona – zatrzymanie procesora w tym miejscu.
}











/*
 * Ta funkcja jest uruchamiana pod spodem, kiedy w swoim kodzie użyjesz funkcji wejściowych,
 * takich jak scanf("%d", &zmienna); albo getchar();. Działa jak "odbiornik paczek".
 * file – descriptor pliku (na STM32 ignorowany).
 * ptr – wskaźnik na miejsce w pamięci RAM, gdzie funkcja ma zapisać to, co uda jej się odebrać.
 * len – informacja od biblioteki C, ile maksymalnie znaków (bajtów) chce w tym momencie przeczytać.
 *
 * (void)file; – Ponownie, uciszamy kompilator, bo nie obchodzi nas, z jakiego "pliku" czytamy.
 * int DataIdx; – Tworzymy zmienną licznikową dla pętli for.
 *
 * Pętla for wykonuje się tyle razy, o ile bajtów poprosiła biblioteka (len).
 *
 * __io_getchar() – Uruchamia funkcję sprzętową (którą sam musisz napisać w main.c),
 * która czeka, aż użytkownik kliknie jakiś klawisz na klawiaturze komputera i prześle
 * ten znak przez UART do STM32.
 *
 * *ptr++ = ... – Odebrany znak jest zapisywany w pamięci pod adresem wskazywanym przez ptr.
 *  Zaraz po zapisie, dzięki dwóm plusom (++), wskaźnik przesuwa się o jedno miejsce dalej,
 *   przygotowując grunt pod kolejną literkę w następnym obrocie pętli.
 *
 *
 */
// Niskopoziomowy odczyt danych (np. wywoływany przez scanf).
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;         // Wyciszenie ostrzeżenia (ignorujemy deskryptor pliku).
  int DataIdx;        // Zmienna indeksu pętli.

  // Pętla czytająca znaki jeden po drugim za pomocą funkcji sprzętowej.
  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar(); // Zapisanie odebranego znaku do bufora i przesunięcie wskaźnika.
  }

  return len;         // Zwrócenie liczby przeczytanych bajtów.
}




/*
 *
 */
// Niskopoziomowy zapis danych (wywoływany m.in. przez printf).
__attribute__((weak)) int _write(int file, char *ptr, int len)		//pobiera dane z printf i przekazuje do oputchara
{
  (void)file;         // Wyciszenie ostrzeżenia (ignorujemy deskryptor pliku).
  int DataIdx;        // Zmienna indeksu pętli.


  /*
   * ptr: Wskaźnik (adres w pamięci), gdzie zaczyna się Twój tekst.
   * len: Informację, ile dokładnie liter (bajtów) ma ten tekst.
   *
   *
   * W tradycyjnych systemach komputerowych (jak Linux), file decyduje, czy piszesz do pliku na dysku, czy na ekran (tzw. stdout). Na mikrokontrolerze zazwyczaj nie masz plików, więc ta zmienna nie jest do niczego potrzebna. Gdybyśmy ją tak po prostu zostawili, kompilator zacząłby marudzić: "Ostrzeżenie: zmienna 'file' została przekazana, ale nigdzie jej nie używasz!". Zapis (void)file; to po prostu sztuczka, która ucisza kompilator.
   */

  // Pętla wysyłająca znaki jeden po drugim.
  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++); // Wysłanie znaku i przesunięcie wskaźnika na kolejny.
    				      //*ptr: Gwiazdka wyciąga wartość (czyli konkretną literę, np. 'C'),
    					  //która znajduje się pod adresem wskazywanym przez ptr.
  }
  return len;         // Zwrócenie liczby zapisanych bajtów.
}





// Zamykanie pliku. Mikrokontroler nie ma systemu plików, więc operacja zawsze się nie udaje.
int _close(int file)
{
  (void)file;   // Wyciszenie ostrzeżenia o nieużywanej zmiennej.
  return -1;    // Zwrócenie błędu.
}






/*
 * Ta funkcja w normalnym systemie operacyjnym (np. Linux) służy do pobierania szczegółowych informacji o
 *  otwartym pliku (np. kiedy został utworzony, jaki ma rozmiar, jakie ma prawa dostępu).
 * int file – to deskryptor (identyfikator) pliku, o który pyta biblioteka C.
 * struct stat *st – to wskaźnik na strukturę (taki formularz), który ta funkcja musi wypełnić danymi o pliku.
 */
// Pobieranie statusu otwartego pliku.
int _fstat(int file, struct stat *st)
{
  (void)file;             // Wyciszenie ostrzeżenia.
  st->st_mode = S_IFCHR;  // Udajemy, że każdy plik to urządzenie znakowe (Character Device, np. UART).
  /*
   * To jest najważniejsza linijka. Odwiedzamy pole st_mode (czyli typ pliku) w formularzu, który dostaliśmy
   * od biblioteki C, i wpisujemy tam flagę S_IFCHR.S_IFCHR to skrót od Status: Inode Function Character –
   * co w ludzkim języku oznacza Character Device (urządzenie znakowe).Urządzenie znakowe to taki byt, który
   * przesyła dane jako ciąg pojedynczych znaków (bajt po bajcie), a nie w dużych blokach (jak dysk twardy).
   * Klasycznym urządzeniem znakowym jest właśnie terminal tekstowy lub port szeregowy UART.Kiedy funkcja
   * printf() startuje, pod spodem wywołuje _fstat, żeby zbadać, gdzie właściwie ma wysłać tekst. Dzięki
   * tej linijce printf dostaje odpowiedź: „Wszystko jest w porządku, ten plik to urządzenie znakowe
   * (terminal)”. printf mówi wtedy: „A, to super, w takim razie przesyłam tekst znak po znaku!” i program
   * działa dalej.
   */
  return 0;               // Zwrócenie sukcesu.
}




/*
 * Biblioteka standardowa C wywołuje tę funkcję, aby zadać proste pytanie:
 * „Czy ten plik (reprezentowany przez numer file), do którego zamierzasz pisać,
 * to interaktywny ekran terminala, czy zwykły plik tekstowy na dysku twardym?”.
 */
// Sprawdzenie, czy deskryptor pliku to terminal (urządzenie interaktywne).
int _isatty(int file)
{
  (void)file;   // Wyciszenie ostrzeżenia.
  return 1;     // Zwraca 1 (prawda) – udajemy, że strumienie wejścia/wyjścia to terminal.
}




/*
 * W systemach operacyjnych takich jak Linux czy Windows, funkcja lseek służy do przesuwania „kursora”
 * (wskaźnika pozycji) wewnątrz otwartego pliku (podobnie jak przewijanie filmu na osi czasu).
 * int file – numer (deskryptor) otwartego pliku.
 * int ptr – przesunięcie, czyli o ile bajtów chcemy się przesunąć.
 * int dir – punkt odniesienia (np. przesuń od początku pliku, od aktualnej pozycji, lub od końca).
 *
 * Ponieważ funkcja na mikrokontrolerze nie ma możliwości realnego przewijania czegokolwiek, żadna z
 * tych zmiennych nie zostanie użyta wewnątrz funkcji. Standardowo, zapis (void) chroni nas przed lawiną
 * ostrzeżeń ze strony kompilatora, który bez tego zarzuciłby programistę komunikatami o nieużywanych
 * argumentach.
 */
// Zmiana pozycji w pliku (przewijanie). Brak obsługi – zawsze zwraca pozycję 0.
int _lseek(int file, int ptr, int dir)
{
  (void)file;   // Wyciszenie ostrzeżenia.
  (void)ptr;    // Wyciszenie ostrzeżenia.
  (void)dir;    // Wyciszenie ostrzeżenia.
  return 0;     // Zwrócenie sukcesu (pozycja 0).
}







/*
 * W standardowych systemach operacyjnych funkcja ta służy do otwierania plików zapisanych na dysku.
 * char *path – ścieżka do pliku, który program chce otworzyć (np. "folder/dane.txt").
 * int flags – tryb otwarcia (np. tylko do odczytu, do zapisu, stwórz jeśli nie istnieje).
 * ... – wielokropek oznacza, że funkcja może przyjąć dodatkowe, opcjonalne argumenty (np. uprawnienia do pliku).
 *
 * Dlaczego tutaj zwracamy błąd -1, skoro _fstat i _lseek „kłamały”, że wszystko jest OK?
 * To bardzo ważna różnica architektoniczna.Funkcje takie jak _fstat, _isatty czy _lseek operują na
 * strumieniach, które już są otwarte i istnieją od momentu uruchomienia mikrokontrolera
 * (są to standardowe strumienie: stdout dla printf oraz stdin dla scanf). One muszą kłamać, żeby te
 * mechanizmy w ogóle ruszyły.Z kolei funkcja _open jest wywoływana wtedy, gdy program próbuje otworzyć
 * jakiś zupełnie nowy, zewnętrzny plik na dysku, pisząc w C na przykład tak:


FILE *f = fopen("konfiguracja.txt", "r");

Gdyby funkcja _open skłamała i zwróciła sukces (0), biblioteka standardowa C pomyślałaby: „Super!
Plik 'konfiguracja.txt' został otwarty!”. W kolejnym kroku program spróbowałby z tego "pliku" czytać za
pomocą funkcji _read. Ale co miałaby wtedy zwrócić funkcja _read? Przecież pliku konfiguracja.txt fizycznie
 nigdzie nie ma w pamięci flash! Program zacząłby czytać losowe śmieci z pamięci lub wysyłać zapytania w
 próżnię, co doprowadziłoby do trudnego do wykrycia błędu lub zawieszenia mikrokontrolera.
Zwrócenie -1 jest bezpiecznikiem: Program od razu dowiaduje się, że operacja się nie udała (fopen zwróci
wskaźnik NULL), dzięki czemu może bezpiecznie zareagować na brak pliku, nie powodując szkód w działaniu systemu.
 *
 *
 */
// Otwieranie nowego pliku.
int _open(char *path, int flags, ...)
{
  (void)path;   // Wyciszenie ostrzeżenia.
  (void)flags;  // Wyciszenie ostrzeżenia.
  /* Pretend like we always fail */
  return -1;    // Udajemy, że otwarcie pliku zawsze kończy się błędem.
}











/*
 * Ta funkcja obsługuje kolejny koncept ze świata zaawansowanych systemów operacyjnych (takich jak Linux)
 * i – podobnie jak funkcja _open – bezkompromisowo zwraca błąd, ponieważ mikrokontroler nie potrafi
 * zarządzać procesami.
 * W systemach operacyjnych funkcja wait służy do synchronizacji procesów. Kiedy program nadrzędny (rodzic)
 * tworzy nowy, niezależny podprogram (proces potomny/dziecko), może użyć tej funkcji, aby dosłownie zatrzymać
 * swoje działanie i poczekać, aż to dziecko skończy pracę.
 * int *status – to wskaźnik na zmienną, do której funkcja ma wpisać informację o tym, jak proces potomny
 * zakończył swoje działanie (np. czy zamknął się poprawnie, czy został ubity przez błąd).
 */
// Oczekiwanie na zakończenie procesu potomnego. Brak procesów na mikrokontrolerze.
int _wait(int *status)
{
  (void)status;   // Wyciszenie ostrzeżenia.
  errno = ECHILD; // Ustawienie błędu: Brak procesów potomnych.	To jest kluczowa linijka logiczna.
  //errno to globalna zmienna przeznaczona do raportowania przyczyn awarii w języku C. Przypisujemy do niej
  //standardowe makro ECHILD (skrót od Error: No child processes – Błąd: Brak procesów potomnych).
  //Mówimy bibliotece C wprost: „Próbujesz czekać na zakończenie podprogramu, ale ty nie masz żadnych dzieci!”.
  return -1;      // Zwrócenie błędu.
}








/*
 * Ta funkcja to kolejny twardy bezpiecznik. Jej zadaniem w standardzie języka C jest usuwanie plików,
 *  ale ponieważ na mikrokontrolerze nie ma dysku ani struktury katalogów, funkcja ta natychmiastowo
 *  odprawia program z kwitkiem.
 */
// Usuwanie pliku z systemu.
int _unlink(char *name)
{
  (void)name;     // Wyciszenie ostrzeżenia.
  errno = ENOENT; // Ustawienie błędu: Brak takiego pliku lub katalogu.
  return -1;      // Zwrócenie błędu.
}









// Pobieranie czasu procesora zużytego przez proces.
int _times(struct tms *buf)
{
  (void)buf;    // Wyciszenie ostrzeżenia.
  return -1;    // Funkcja nieobsługiwana, zwraca -1.
}



// Pobieranie statusu pliku na podstawie jego ścieżki (nazwy).
int _stat(char *file, struct stat *st)
{
  (void)file;             // Wyciszenie ostrzeżenia.
  st->st_mode = S_IFCHR;  // Podobnie jak w _fstat, udajemy urządzenie znakowe.
  return 0;               // Zwrócenie sukcesu.
}











/*
 * W tradycyjnych systemach operacyjnych funkcja ta służy do tworzenia tzw. twardego dowiązania (hard link).
 * Pozwala to na stworzenie nowej nazwy (new) dla istniejącego już pliku (old). W efekcie ten sam plik jest
 * widoczny w systemie w dwóch różnych miejscach pod różnymi nazwami, ale fizycznie na dysku istnieje tylko raz.
 * char *old – ścieżka do istniejącego pliku źródłowego.
 * char *new – ścieżka do nowego dowiązania, które chcemy utworzyć.
 *
 *
 * To jest najciekawszy element tej funkcji. Do globalnej zmiennej systemowej errno przypisujemy standardowy
 * kod błędu EMLINK.Skrót ten pochodzi od angielskiego Error: Too many links (Błąd: Zbyt wiele dowiązań).
 * W systemach operacyjnych ten błąd pojawia się normalnie wtedy, gdy plik osiągnie maksymalną dopuszczalną
 * liczbę twardych dowiązań (w wielu systemach limit ten wynosi 65 000).Mikrokontroler używa tego kodu jako
 * sprytnej wymówki. Mówi bibliotece standardowej C: „Nie mogę utworzyć nowego dowiązania, ponieważ limit
 * linków dla tego obiektu został już wyczerpany!”.
 * Zgodnie ze standardem POSIX, zwrócenie wartości -1 jednoznacznie informuje program wywołujący, że
 * operacja zlinkowania plików się nie powiodła.
 */
// Tworzenie twardego linku do pliku.
int _link(char *old, char *new)
{
  (void)old;       // Wyciszenie ostrzeżenia.
  (void)new;       // Wyciszenie ostrzeżenia.
  errno = EMLINK;  // Ustawienie błędu: Zbyt wiele dowiązań.
  return -1;       // Zwrócenie błędu.
}




/*
 * Ta funkcja blokuje jedną z najbardziej fundamentalnych operacji wielozadaniowości,
 * jakie znamy ze systemów operacyjnych typu Linux – czyli klonowanie procesów. Podobnie
 *  jak w przypadku funkcji _wait, mikrokontroler natychmiastowo i twardo odrzuca tę operację.
 *  W systemach operacyjnych funkcja fork() służy do tworzenia nowego procesu. Działa to w fascynujący sposób:
 *   istniejący program (proces-rodzic) wywołuje fork(), a system operacyjny dosłownie klonuje go w pamięci RAM.
 *  Od tego momentu w systemie działają dwa identyczne programy (rodzic i dziecko), które wykonują kod od
 *  tego samego miejsca, ale mają osobne, odizolowane pamięci.
 *  (void) – funkcja nie przyjmuje żadnych argumentów.
 *
 *  To jest kluczowy komunikat dla biblioteki standardowej C. Do globalnej zmiennej systemowej errno
 *  przypisujemy kod błędu EAGAIN.Skrót ten pochodzi od angielskiego Error: Try again (Błąd: Spróbuj ponownie).
 *  W klasycznych systemach ten błąd oznacza: „W systemie skończyły się zasoby (np. pamięć RAM lub limit
 *  procesów), aby stworzyć nowy proces. Spróbuj ponownie za chwilę”.Mikrokontroler używa tego kodu jako
 *  idealnej, dyplomatycznej wymówki. Nie mówi programowi: „Jestem tylko małym procesorem i nie mam
 *  systemu operacyjnego”, tylko posługuje się profesjonalnym językiem POSIX: „Chętnie bym cię sklonował,
 *  ale w tym momencie nie mam na to zasobów, spróbuj później”.
 */
// Tworzenie nowego procesu (klonowanie).
int _fork(void)
{
  errno = EAGAIN; // Ustawienie błędu: Spróbuj ponownie / Brak zasobów na nowy proces.
  return -1;      // Zwrócenie błędu.
}




/*
 * W prawdziwym systemie operacyjnym ta funkcja służy do uruchomienia zupełnie nowego programu w miejsce
 * bieżącego. Kiedy wpisujesz w konsoli komputera np. ls lub klikasz ikonę gry, system najpierw robi fork()
 * (klonuje proces), a potem wewnątrz tego klona wywołuje execve(), aby załadować plik wykonywalny z dysku.
 * char *name – ścieżka do pliku wykonywalnego, który program chce uruchomić (np. "/bin/program.exe").
 * char argv – tablica argumentów przekazywanych do nowego programu (to, co w main odbierasz jako argv).
 * char env – tablica zmiennych środowiskowych, w których nowy program ma zostać uruchomiony (powiązana z
 * zmienną environ, o której rozmawialiśmy na początku).
 *
 * Ponieważ mikrokontroler nie ma dysku, z którego mógłby załadować nowy program, ani systemu, który potrafiłby
 *  go uruchomić, wszystkie te trzy zaawansowane argumenty są dla niego bezużyteczne. Rzutowanie na (void)
 *  chroni Twój projekt przed lawiną ostrzeżeń ze strony kompilatora.
 *
 *  To jest bardzo ciekawa i sprytna zagrywka architektów kodu STM32. Do globalnej zmiennej systemowej errno przypisują kod błędu ENOMEM.

Skrót ten pochodzi od angielskiego Error: No memory (Błąd: Brak pamięci / Out of memory). Mikrokontroler
ponownie używa dyplomatycznego języka POSIX. Nie mówi: "Nie mam pojęcia, jak odpalić plik .exe", tylko
zrzuca winę na zasoby: „Próbowałem załadować program, o który prosisz, ale niestety zabrakło mi wolnej
pamięci RAM, aby go pomieścić”.
 */
// Uruchamianie innego programu w miejscu bieżącego procesu.
int _execve(char *name, char **argv, char **env)
{
  (void)name;     // Wyciszenie ostrzeżenia.
  (void)argv;     // Wyciszenie ostrzeżenia.
  (void)env;      // Wyciszenie ostrzeżenia.
  errno = ENOMEM; // Ustawienie błędu: Brak pamięci.
  return -1;      // Zwrócenie błędu.
}
